export const IndividualCards = [
    {
        id : 1,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 2,
        venue: "Shah Alam",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 3,
        venue: "Sportizza",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 4,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 5,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 6,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 7,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 8,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 9,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 10,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 11,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 12,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 13,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 14,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 15,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
    {
        id : 16,
        venue: "Kota Damansara",
        date: "21/8/2020",
        time: "10pm -11pm",
        joinLink: "",
    },
]